- name: Deploy Wordpress and MYSQL
  hosts: all
  vars:
    MYSQL_ROOT_PASSWORD: "dsad2142ad@$@1f"
  tasks:

    - name: Create Network
      community.docker.docker_network:
        name: wordpress

    - name: Create Volumes
      community.docker.docker_volume:
        name: wordpress

    - name: Create Volumes
      community.docker.docker_volume:
        name: db

    - name: Deploy Wordpress
      community.docker.docker_container:
        name: wordpress
        image: wordpress:latest
        ports:
          - "80:80"
        networks:
          - name: wordpress
        volumes:
          - wordpress:/var/www/html
        env:
          WORDPRESS_DB_HOST: "db"
          WORDPRESS_DB_USER: "fonteyn"
          WORDPRESS_DB_PASSWORD: "dsad2142ad@$@1f3"
          WORDPRESS_DB_NAME: "fonteyndb"

    - name: Deploy MYSQL
      community.docker.docker_container:
        name: db
        image: mysql:5.7
        networks:
          - name: wordpress
        volumes:
          - db:/var/lib/mysql
        env:
          MYSQL_ROOT_PASSWORD: "{{ dsad2142ad@$@1f }}"
          MYSQL_DATABASE: "fonteyndb"
          MYSQL_USER: "fonteyn"
          MYSQL_PASSWORD: "dsad2142ad@$@1f2"
