---
- name: Update Docker container to Nextcloud
  hosts: all
  become: true
  tasks:
    - name: Stop and remove existing container
      command: |
        docker stop docker4
        docker rm docker4

    - name: Pull Nextcloud image
      command: docker pull nextcloud:latest

    - name: Run container as Nextcloud server
      command: |
        docker run -d -p 80:80 -p 443:443 --name docker4 -v /nextcloud/data:/var/www/html/data -v /nextcloud/config:/var/www/html/config -v /nextcloud/apps:/var/www/html/apps nextcloud:latest
