- name: Set up Docker container as web server
  hosts: all
  become: true
  tasks:
    - name: Stop and remove existing container
      command: |
        docker stop docker1
        docker rm docker1

    - name: Pull web server image
      command: docker pull httpd:latest

    - name: Run container as web server
      command: |
        docker run -d -p 80:80 -p 443:443 --name docker1 -v /etc/ssl:/etc/ssl:ro -v /etc/httpd:/etc/httpd:ro -v /var/www:/var/www httpd:latest httpd-foreground
