---
- hosts: all
  become: yes
  tasks:
  - name: Install Apache2
    apt:
      name: apache2
      state: latest

  - name: Generate self-signed SSL certificate
    command: openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/apache-selfsigned.key -out /etc/ssl/certs/apache-selfsigned.crt -subj "/C=US/ST=California/L=San Francisco/O=Example Company/OU=IT Department/CN=example.com"
    args:
      creates: /etc/ssl/private/apache-selfsigned.key

  - name: Create simple HTML website
    copy:
      content: |
        <html>
        <head>
          <title>Welcome to my website!</title>
        </head>
        <body>
          <h1>Hello, world!</h1>
          <p>This is a simple HTML website.</p>
        </body>
      dest: /var/www/html/index.html

  - name: Enable SSL module
    command: a2enmod ssl
    args:
      creates: /etc/apache2/mods-enabled/ssl.load

  - name: Create SSL virtual host
    template:
      src: ssl-virtual-host.conf.j2
      dest: /etc/apache2/sites-available/ssl-virtual-host.conf
    notify:
    - restart apache2

  - name: Enable SSL virtual host
    command: a2ensite ssl-virtual-host
    args:
      creates: /etc/apache2/sites-enabled/ssl-virtual-host.conf
      remove: /etc/apache2/sites-enabled/000-default.conf

  - name: Start Apache2 service
    service:
      name: apache2
      state: started
  handlers:
  - name: restart apache2
    service:
      name: apache2
      state: restarted
